version: "3.8"
services:
  app:
    container_name: app-lightning-atm-mainan-ui
    image: inanimate/httpd-ssl
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.middlewares.fix-prefix.stripprefix.prefixes=/"
      - "traefik.http.middlewares.fix-the-trailing.redirectregex.regex=((?:.*([/][0-9a-z_-]{1,})$$).*$$)"
      - "traefik.http.middlewares.fix-the-trailing.redirectregex.replacement=$${1}/"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.middlewares.app-ratelimit.ratelimit.burst=15"
      - "traefik.http.routers.app-secure.rule=((Host(`beta.roaringstars.com`) || Host(`labs.roaringstars.com`)) && PathPrefix(`/`))"
      - "traefik.http.routers.app-secure.middlewares=fix-prefix,fix-the-trailing"
      - "traefik.http.middlewares.app-ratelimit.ratelimit.average=25"
    ports:
      - 5030:443
      - 1030:80
    networks:
      - public
    restart: always
    mem_limit: 10m

networks:
  public:
    external: true